# -*- coding: utf-8 -*-
"""Trying w MRI Data

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/147tFM3MNyxC6gi31qUhkm3629Uqm5RuT
"""

!git clone https://github.com/mahabubul-alam/iccad_2021_invited_QML



!pip install pennylane

# Commented out IPython magic to ensure Python compatibility.
# %cd iccad_2021_invited_QML/

!python run.py

